= DukeCon Kubernetes / Jenkins-X Demo
:author: Gerd Aschemann
:email: gerd@aschemann.net
:twitter: @GerdAschemann
:lang: en
:icons: font
:aws:false

[.lead]
====
You have some Dev or Ops background and want to learn about one or all of the following?

* https://jenkins-x.io[Jenkins-X] (JX) - next generation Kubernetes based CI/CD solution provided by the makers of the famous https://jenkins.io[Jenkins] server?
* https://kubernetes.io[Kubernetes] (k8s) - the _Cloud Operating System_?
* Development and deployment of a cloud native (distributed) application to k8s with the help of JX - by the example of https://dukecon.org[DukeCon], the conference planner for Javaland and other community based conferences?

We will (currently) introduce you to experience these goals by some hands-on tutorials and open space sessions, e.g.,
at https://www.javaland.eu/de/programm/community-aktivitaeten/[Javaland 2020].
====

The class does not require to be a Java developer but some Java background will help to understand the examples.

[WARNING]
This is currently not a complete online tutorial to introduce you to the mentioned technologies and goals.
It only provides an introduction to enable you to participate in an hands-on session at one of the mentioned events.

:toc:

[[prerequisites]]
== Prerequisites

.TL;DR
****
If you are experienced to run a local machine with OSX or Linux (even as a VM) and install and use developer and operator tools, you may directly jump to the respective <<setup,installation and preparation>> parts for

* <<cloud-account>>,
* <<local-tools>>, and
* <<github-account>>.
****

[CAUTION]
====
*Medium Level Skills minimum*: The class is aiming at people with at least medium level development or operations experience.
You should be used to work with tools like Git, a Shell and an IDE (optional, at least an Editor like `vi` or `emacs` is required).

*Local Administrator Rights required:* Furthermore, you need to be able to run administrative tasks on your machine like installing the required <<local-tools>>.
We are not able to explain in detail the installation of the tools.
You may use it as a first check if you are able to follow the class, iff you are able to complete the requirements section and install the tools and accounts.
====

To take part of the session you need to prepare the following tools and accounts.
You need to run some small tools from either a local machine (Laptop) or a network (cloud) machine where you have shell access.
Your local machine does not need to be extremely powerful, though we recommend to have at least 8 GB of RAM to run a local Java IDE (IntelliJ) if desired.
The _real work_ is performed by some cloud provider, e.g., GCP or AWS.

[TIP]
====
We strongly recommend to make use of a Unix-like operating systems, e.g., OSX (MacOS) or Linux.

[[windows]]
.Windows Users
****
If you need to work with Windows, you should at least have a `bash` (e.g., provided by https://git-scm.com/download/win[git for Windows]).
Better results should be possible with Windows Linux Subsystem (WLS) as enabled by Windows 10.

*Note*: We are not able to test a git bash or WLS based install due to a lack of access to a respective machine.
If you have the possibility to run this setup with Win10, we are happy about a change request to https://github.com/dukecon/dukecon-jx-demo[this repository]!

If all else fails please consider installing a small VM (2 GB RAM) with Linux (Ubuntu or Debian).
You may use Vagrant (cf. <<vagrant>>) and VirtualBox to set it up.
****

If you have a remote Linux machine (in the cloud) available you may also use it. Please make sure you have your cloud credentials on this machine.
====

[[setup]]
[[cloud-account]]
=== Cloud Account

K8s can be run on a great variety of public clouds as well as on-premises and you probably have a private cloud with k8s already at hand?
You may even consider running k8s on your local machine by Vagrant/VirtualBox, Qemu, or Minikube.
JX also claims to run with an increasing number of cloud providers.

Nevertheless, from our experience the _big_ cloud providers Google Cloud Platform (GCP) and Amazon Web Services (AWS) provide the best way to complete the examples.
According to our experiences they both provide the most stable environments (for JX) and the fastest infrastructure.
Please get yourself one of the following accounts and perform the necessary steps to install k8s and JX on your account.

==== GCP / GKE account

[NOTE]
.GKE
====
On the Google Cloud Platform we will use a managed Kubernetes, called Google Kubernetes Engine (GKE).
====

* Create a Google cloud account if you do not already have one: https://cloud.google.com/[]
** Google provides a free plan for some time (cf. https://cloud.google.com/free/[]),
** You need a Google user account if you do not have one already (may be created in the course of the cloud account setup).
* Install the `gcloud` SDK:
** You may try the link:bin/install-gcloud[] shell script (at least for Ubuntu/Debian),
** *or* Follow the instructions in https://cloud.google.com/sdk/docs/quickstarts[]

==== AWS / EKS account

ifdef::aws[]
[NOTE]
.EKS
====
In the Amazon Web Services cloud we will use a managed Kubernetes, called Elastic Kubernetes Services (EKS).
====

* Create AWS cloud account if you do not already have one:
** AWS provides a free plan fo some time (cf. https://aws.amazon.com/free/[])
** Press the _Create a Free Account_ button https://aws.amazon.com/free/[there]
* Install `eksctl`:
** You may try the link:bin/install-eks[] shell script (at least for Ubuntu/Debian or OSX),
** *or* Follow the instructions in https://eksctl.io/usage/creating-and-managing-clusters/[]

endif::aws[]
ifndef::aws[]

[IMPORTANT]
====
Amazon Setup will be completed soon!
====
endif::aws[]

[[local-tools]]
=== Local Tools

[NOTE]
If we talk of local tools or _a local machine_, a remote machine with shell access is also covered.

* Checkout (clone) this repository from https://github.com/dukecon/dukecon-jx-demo

Please install the following tools

* a Shell (e.g., git `bash`, when running on Windows (<<windows>>))
* `git` (should be pre-installed on most OS distributions)
* `hub` (a nice CLI tool to work with GitHub from your local shell)
* `screen` (optional, not only helpful if running on Vagrant and/or remote machine, but also to share environments for parallel terminal sessions)
* `jx`
** Try to run the link:bin/install-jx[] shell script, *or*
** Follow the instructions in https://jenkins-x.io/docs/getting-started/setup/install/[]
* Optionally install/move/link the following tools.
By default `jx` will install them to ~/.jx/bin.
If you want to have them available in your binary search path, you may want to link or move them to, e.g., `/usr/local/bin`.
** General:
*** `kubectl` (https://kubernetes.io/docs/tasks/tools/install-kubectl/[])
//** GCP
//*** TBD
ifdef::aws[]
//** AWS
//*** `kops`,
//*** and `aws` (optional)
endif::aws[]
** Optional
*** `helm` (helpful for debugging problems)

[[github-account]]
=== Github Account

If you do not have a https://github.com[Github] account, create one (free).

== Getting started

[CAUTION]
====
If you can't wait for the tutorial day to start, you may proceed on your own risk from here.
Be aware that setting up infrastructure/resources in your cloud account may cause fees being charged to you depending on the kind of resources (machines, IPs, load balancers etc.) and if you have a free plan.

.Remove resources when you're done!
****
If you are finished with your work you probably want to remove your cloud resources in order to avoid being charged by the cloud provider, cf. <<cleanup>>.
****
====

[[prepare-cloud]]
=== Prepare your Cloud Account

Log in to your cloud account and perform further setup

GKE::
* `gcloud auth login` # This will either open a browser session or show (a long) URL (please open with browser then) and follow instructions
* Create a new project: https://console.cloud.google.com/projectcreate[], e.g., `jx-demo`
* Smoketest: Check if the project is created with `gcloud projects list`
* Set the new project as default: `gcloud config set project <project>`
ifdef::aws[]
AWS::
TBD
endif::aws[]

=== Create Jenkins X

Run the following command to get your first cluster going (you may follow almost all defaults of the interactive wizard):

GKE::
* `jx create cluster gke --skip-login` (make sure the login went well in <<prepare-cloud,the prepare step>>)
ifdef::aws[]
AWS::
TBD
endif::aws[]

[appendix]
[[cleanup]]
== Cleanup

=== Destroy Cloud Infrastructure

If you want to destroy your cluster, please perform the following commands.

GKE::
** `gcloud container clusters list` # Then check the name and zone (Location) of your created cluster here
** `gcloud container clusters delete -z <location> <name>` # insert location and name
** `jx gc gke` # This creates a local cleanup script `gc_gke.sh`
** `./gc_gke.sh` # Execute final cleanup
ifdef::aws[]
AWS::
TBD
endif::aws[]

=== Hibernate Cloud Infrastructure

TBD

[appendix]
[[vagrant]]
== Vagrant Setup

We have prepared a https://www.vagrantup.com/[Vagrant] Virtual Machine setup for your convenience if you do not have the opportunity to run on OSX/Linux or if you do not want to leave any of the tools on your local machine.
Just go to the root of this repository (your local clone of it) and run

* `./bin/vagrant-init` (may take some time if you have to download the vagrant box for the first time),
* `vagrant ssh` to log into the new VM.

Proceed from here with the additional setup (cf. <<prerequisites>>).

[appendix]
== Links

* https://jenkins-x.io/docs/getting-started/setup/[Setup Jenkins-X]
